# Elixir CircleCI 2.0 configuration file
# https://onboarding.circleci.com/project-setup/github/thiagogsr/voting
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.10.1
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11.5-alpine

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force # install Hex locally (without prompt)
      - run: mix local.rebar --force # fetch a copy of rebar (without prompt)
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix do deps.get, deps.compile
      - save_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - ~/.mix
            - _build
      - run: mix compile --warnings-as-errors
      - run: # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix do ecto.create, ecto.migrate
      - run: mix test
      - run: mix format --check-formatted
      - run: mix credo --strict